# 支持零配置启动，即无需填写配置默认启用所有的插件。

global:
  console:
    secret: "ab0f6913670062af4d2f15c62120517c"
  # http:
  #   listenaddrtls: :8081
  #   certfile: monibuca.com.pem
  #   keyfile: monibuca.com.key
webtransport:
  enable: false
rtsp:
  enable: false
  pull:
    pullonstart: true
    pulllist:
      live/rtsp: rtsp://admin:MOMA2021@47.94.226.17/Streaming/Channels/201?transportmode=unicast
