// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monibuca.proto

package monibuca

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Streamid             int32    `protobuf:"varint,4,opt,name=streamid,proto3" json:"streamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayRequest) Reset()         { *m = PlayRequest{} }
func (m *PlayRequest) String() string { return proto.CompactTextString(m) }
func (*PlayRequest) ProtoMessage()    {}
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb7cc46349543379, []int{0}
}

func (m *PlayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayRequest.Unmarshal(m, b)
}
func (m *PlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayRequest.Marshal(b, m, deterministic)
}
func (m *PlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayRequest.Merge(m, src)
}
func (m *PlayRequest) XXX_Size() int {
	return xxx_messageInfo_PlayRequest.Size(m)
}
func (m *PlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayRequest proto.InternalMessageInfo

func (m *PlayRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlayRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PlayRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PlayRequest) GetStreamid() int32 {
	if m != nil {
		return m.Streamid
	}
	return 0
}

type PlayResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayResponse) Reset()         { *m = PlayResponse{} }
func (m *PlayResponse) String() string { return proto.CompactTextString(m) }
func (*PlayResponse) ProtoMessage()    {}
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb7cc46349543379, []int{1}
}

func (m *PlayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayResponse.Unmarshal(m, b)
}
func (m *PlayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayResponse.Marshal(b, m, deterministic)
}
func (m *PlayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayResponse.Merge(m, src)
}
func (m *PlayResponse) XXX_Size() int {
	return xxx_messageInfo_PlayResponse.Size(m)
}
func (m *PlayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayResponse proto.InternalMessageInfo

type StopRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Streamid             int32    `protobuf:"varint,2,opt,name=streamid,proto3" json:"streamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb7cc46349543379, []int{2}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StopRequest) GetStreamid() int32 {
	if m != nil {
		return m.Streamid
	}
	return 0
}

type StopResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb7cc46349543379, []int{3}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func (m *StopResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PullRequest struct {
	Streamid             int32    `protobuf:"varint,1,opt,name=streamid,proto3" json:"streamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullRequest) Reset()         { *m = PullRequest{} }
func (m *PullRequest) String() string { return proto.CompactTextString(m) }
func (*PullRequest) ProtoMessage()    {}
func (*PullRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb7cc46349543379, []int{4}
}

func (m *PullRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullRequest.Unmarshal(m, b)
}
func (m *PullRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullRequest.Marshal(b, m, deterministic)
}
func (m *PullRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullRequest.Merge(m, src)
}
func (m *PullRequest) XXX_Size() int {
	return xxx_messageInfo_PullRequest.Size(m)
}
func (m *PullRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullRequest proto.InternalMessageInfo

func (m *PullRequest) GetStreamid() int32 {
	if m != nil {
		return m.Streamid
	}
	return 0
}

type PullResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullResponse) Reset()         { *m = PullResponse{} }
func (m *PullResponse) String() string { return proto.CompactTextString(m) }
func (*PullResponse) ProtoMessage()    {}
func (*PullResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb7cc46349543379, []int{5}
}

func (m *PullResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullResponse.Unmarshal(m, b)
}
func (m *PullResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullResponse.Marshal(b, m, deterministic)
}
func (m *PullResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullResponse.Merge(m, src)
}
func (m *PullResponse) XXX_Size() int {
	return xxx_messageInfo_PullResponse.Size(m)
}
func (m *PullResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PlayRequest)(nil), "monibuca.PlayRequest")
	proto.RegisterType((*PlayResponse)(nil), "monibuca.PlayResponse")
	proto.RegisterType((*StopRequest)(nil), "monibuca.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "monibuca.StopResponse")
	proto.RegisterType((*PullRequest)(nil), "monibuca.PullRequest")
	proto.RegisterType((*PullResponse)(nil), "monibuca.PullResponse")
}

func init() { proto.RegisterFile("monibuca.proto", fileDescriptor_fb7cc46349543379) }

var fileDescriptor_fb7cc46349543379 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xcd, 0x4e, 0xc4, 0x20,
	0x18, 0x5c, 0x70, 0x35, 0xeb, 0xd7, 0x4d, 0x0f, 0x24, 0x1a, 0xb2, 0x07, 0xb3, 0xe1, 0xb4, 0x5e,
	0xf6, 0xa0, 0x07, 0xe3, 0x5b, 0x6c, 0xea, 0x13, 0x50, 0xe1, 0x40, 0xd2, 0x16, 0xca, 0x4f, 0x8c,
	0x0f, 0xe6, 0xfb, 0x19, 0x8a, 0x45, 0xda, 0x18, 0x8f, 0xf3, 0x7d, 0xcc, 0x7c, 0x33, 0x03, 0xd4,
	0xbd, 0x1e, 0x54, 0x1b, 0xde, 0xf9, 0xd9, 0x58, 0xed, 0x35, 0xd9, 0xcd, 0x98, 0x8d, 0x50, 0x5d,
	0x3a, 0xfe, 0xd9, 0xc8, 0x31, 0x48, 0xe7, 0x49, 0x0d, 0x58, 0x09, 0x8a, 0x8e, 0xe8, 0x74, 0xdb,
	0x60, 0x25, 0xc8, 0x01, 0x76, 0xc1, 0x49, 0x3b, 0xf0, 0x5e, 0x52, 0x3c, 0x4d, 0x33, 0x8e, 0x3b,
	0xc3, 0x9d, 0xfb, 0xd0, 0x56, 0xd0, 0xab, 0xb4, 0x9b, 0x71, 0xdc, 0x39, 0x6f, 0x25, 0xef, 0x95,
	0xa0, 0xdb, 0x23, 0x3a, 0x5d, 0x37, 0x19, 0xb3, 0x1a, 0xf6, 0xe9, 0xa4, 0x33, 0x7a, 0x70, 0x92,
	0xbd, 0x42, 0xf5, 0xe6, 0xb5, 0xf9, 0xc7, 0x42, 0x96, 0xc2, 0x2b, 0xa9, 0x07, 0xd8, 0x27, 0x6a,
	0x92, 0x5a, 0x73, 0xd9, 0x23, 0x54, 0x97, 0xd0, 0x75, 0xb3, 0x74, 0x29, 0x85, 0xfe, 0x70, 0x35,
	0x3d, 0x4d, 0x52, 0x4f, 0x5f, 0x08, 0x72, 0x4b, 0xe4, 0x05, 0xb6, 0xd1, 0x32, 0xb9, 0x3b, 0xe7,
	0x22, 0x8b, 0xd6, 0x0e, 0xf7, 0xeb, 0xf1, 0x4f, 0xb2, 0x4d, 0x24, 0x46, 0x83, 0x25, 0xb1, 0xc8,
	0x5a, 0x12, 0xcb, 0x1c, 0x89, 0x18, 0xed, 0x2c, 0x2e, 0xfe, 0x26, 0x59, 0x5c, 0x2c, 0x5c, 0xb3,
	0x4d, 0x7b, 0x33, 0xfd, 0xf0, 0xf3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xe0, 0x47, 0x0d,
	0xf3, 0x01, 0x00, 0x00,
}
